### ISSUE TITLE
Auto-Enable Mod Dependencies

### ISSUE THREAD

**Issue by dreambones** [Bwc9876/ow-mod-man#51]
### Package

Graphical Interface

### Feature

Automatically enabling dependencies for a mod you enable would be a small but nice touch. But since that would stop people from knowing *what* that mod's dependencies are, another visual indicator would be required.

**Comment by Bwc9876** [comment]
There's no good way to do this with just a visual indicator. At most, we could add a dialog asking if the user wishes to enable dependencies as well (only if the mod has dependencies that are disabled of course). Another solution could be to put this behavior behind a setting.

**Comment by Bwc9876** [comment]
I think what I'll go with here is a dialog box when you enable a mod that'll ask if you want to also enable dependencies. And then a GUI setting that makes it always happen with no confirmation
