### ISSUE TITLE
Add optional support for dragon (xdragon)

### ISSUE THREAD

**Issue by loco-choco** [Bwc9876/ow-mod-man#60]
### Package

Command Line Interface

### Feature

[Dragon (xdragon)](https://github.com/mwh/dragon) is a command line too that allows you to drag and drop files and urls to the command line, and would be cool if it was integrated in some way for passing, for example, urls of mods to install in `owmods install-url`, or to drag out the json from `owmods export`. Maybe you could activate it with some kind of flag like `--dragon`.

### Platform

Linux

**Comment by Bwc9876** [comment]
I think this could be better off made as a reusable script that users can place in their `.bashrc` or similar, the [example script they provide](https://github.com/mwh/dragon/blob/master/example/download.sh) is basically all we need, just replace "wget $url" with "owmods iu $url".

**Comment by loco-choco** [comment]
True, sadly we can't get dragging out working without creating a temp file, from what https://github.com/mwh/dragon/issues/61 suggests, so we would need to have the script have that.
