### ISSUE TITLE
File watch refresh breaks if settings window is open

### ISSUE THREAD

**Issue by JohnCorby** [Bwc9876/ow-mod-man#62]
### What Happened?

When I update a mod, and the file watcher triggers a refresh, it closes the settings modal, but I cannot interact with the main window

### Package

Graphical Interface

### Platform

Windows

**Comment by Bwc9876** [comment]
This is most likely gonna be fixed when I complete #61, so I'm not gonna mention it in the change log. Just know next version it'll be fixed
