### ISSUE TITLE
Improve settings load error

### ISSUE THREAD

**Issue by Raicuparta** [Bwc9876/ow-mod-man#65]
### Package

Graphical Interface

### Feature

![image](https://github.com/Bwc9876/ow-mod-man/assets/3955124/204133e9-db1c-4674-949c-755a4be7bd4e)

this error can be one of three things: main config, gui config, owml config. The error should specify which one is broken and offer to reset to defaults. It could also not specify it but at least offer to reset everything.

**Comment by Bwc9876** [comment]
Going to be redoing a lot of the error handling to use error boundaries so this should hopefully get better with that.

**Comment by Bwc9876** [comment]
Ok, now if the OWML config is messed up, it will put the error in the modal and offer to reset. If the other two are messed up it'll put the mistake in the entire app (we failed to load the info we need to render the app after all), but I won't be able to offer to reset the settings, best I can do is point to the files that need to be deleted/fixed.
