### ISSUE TITLE
Stuff not marked as outdated when manager starts up

### ISSUE THREAD

**Issue by Raicuparta** [Bwc9876/ow-mod-man#69]
### What Happened?

![image](https://github.com/Bwc9876/ow-mod-man/assets/3955124/4bff4706-446f-441c-8c76-81d01a1313cf)

Pressing refresh fixes it:
![image](https://github.com/Bwc9876/ow-mod-man/assets/3955124/f0f73d07-cc06-46b0-b9db-9beae24f7588)

Same happens in installed mods tab

### Package

Graphical Interface

### Platform

Linux

**Comment by Bwc9876** [comment]
This is most likely a race condition in which the local database checks for updates before the remote one has a chance to propagate. Might make it so the validation for updates is run on both local and remote refresh.
